name: Fuzz Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fuzz:
    runs-on: ubuntu-latest  # This specifies the runner environment (Ubuntu)

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (if needed)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          

      # Step 4: Run fuzz.py from the mining directory
      - name: Run fuzz.py
        run: |
          python mining/fuzz.py  # Run fuzz.py using the relative path
